import { SupabaseClient } from '@supabase/supabase-js';
import { Writable } from 'stream';
import React from 'react';

export interface AdrRecord { number: string; slug: string; content: string; }
export interface EnvFiles { frontend: string; backend: string; example: string; }

function getPdfFilename(slug: string, version: number): string {
  const date = new Date().toISOString().split('T')[0];
  return slug + '_specification_v' + version + '_' + date + '.pdf';
}

function getZipFilename(slug: string): string {
  const date = new Date().toISOString().split('T')[0];
  return 'linup_' + slug + '_' + date + '.zip';
}

async function assembleSpecData(projectId: string, stages: number[], db: SupabaseClient): Promise<any> {
  const { data: project } = await db.from('projects').select('name, slug, identity_json').eq('id', projectId).single();
  const { data: consolidations } = await db.from('stage_consolidations').select('stage, consolidation_json').eq('project_id', projectId).in('stage', stages).order('stage');
  const { data: pltOutputs } = await db.from('stage_runs').select('stage, plt_output_json').eq('project_id', projectId).in('stage', stages).order('stage');
  const { data: founderAnswers } = await db.from('founder_answers').select('stage, question_id, answer').eq('project_id', projectId).order('stage');
  const { data: rtmEntries } = await db.from('rtm_entries').select('req_id, stage, status, notes').eq('project_id', projectId).order('stage');
  return { project, consolidations: consolidations ?? [], pltOutputs: pltOutputs ?? [], founderAnswers: founderAnswers ?? [], rtmEntries: rtmEntries ?? [] };
}

// generateSpecPdf — uses React.createElement (no JSX in .ts files)
// Doc 7D: @react-pdf/renderer, styles per spec
export async function generateSpecPdf(projectId: string, stages: number[], db: SupabaseClient): Promise<Buffer> {
  const { renderToBuffer, Document, Page, Text, View, StyleSheet } = await import('@react-pdf/renderer');
  const data = await assembleSpecData(projectId, stages, db);
  const projectName = data.project?.name ?? 'Untitled Project';
  const ce = React.createElement;

  const styles = StyleSheet.create({
    page:      { fontFamily: 'Helvetica', fontSize: 10, padding: 40, backgroundColor: '#FFFFFF' },
    h2:        { fontSize: 16, fontWeight: 'bold', marginBottom: 8, marginTop: 16 },
    body:      { fontSize: 10, lineHeight: 1.5, marginBottom: 8 },
    coverPage: { backgroundColor: '#0C0C0E', height: '100%', padding: 60 },
    coverTitle:{ color: '#FFFFFF', fontSize: 32, fontWeight: 'bold', marginTop: 120 },
    coverMeta: { color: '#9CA3AF', fontSize: 12, marginTop: 16 },
  });

  const coverPage = ce(Page, { style: styles.coverPage },
    ce(View, { style: styles.coverTitle }, ce(Text, null, projectName + ' — Engineering Specification')),
    ce(View, { style: styles.coverMeta }, ce(Text, null, 'Generated by LINUP v2 — ' + new Date().toLocaleDateString('en-GB')))
  );

  const stagePages = (data.consolidations as any[]).map((c: any) =>
    ce(Page, { style: styles.page },
      ce(View, { style: styles.h2 }, ce(Text, null, 'Stage ' + c.stage + ' — ' + (c.consolidation_json?.stageName ?? ''))),
      ce(View, { style: styles.body }, ce(Text, null, JSON.stringify(c.consolidation_json, null, 2)))
    )
  );

  const doc = ce(Document, null, coverPage, ...stagePages);
  return renderToBuffer(doc as any);
}

async function generateRtmCsv(projectId: string, db: SupabaseClient): Promise<string> {
  const { data } = await db.from('rtm_entries').select('req_id, stage, status, notes').eq('project_id', projectId).order('stage');
  const rows = (data ?? []).map((r: any) => r.req_id + ',' + r.stage + ',' + r.status + ',' + (r.notes ?? '').replace(/,/g, ';'));
  return 'req_id,stage,status,notes\n' + rows.join('\n');
}

export async function generateAppPackageZip(projectId: string, db: SupabaseClient): Promise<Buffer> {
  const archiver = (await import('archiver')).default;
  const chunks: Buffer[] = [];
  const output = new Writable({ write(chunk: Buffer, _enc: string, cb: () => void) { chunks.push(chunk); cb(); } });
  const archive = archiver('zip', { zlib: { level: 9 } });
  archive.pipe(output);
  const allStages = [0,1,2,3,4,5,6,7,8,9,10,11,12];
  const specPdf = await generateSpecPdf(projectId, allStages, db);
  archive.append(specPdf, { name: 'specification/complete_specification.pdf' });
  const rtmCsv = await generateRtmCsv(projectId, db);
  archive.append(rtmCsv, { name: 'specification/requirements_traceability.csv' });
  const { data: project } = await db.from('projects').select('name, slug').eq('id', projectId).single();
  const readme = '# ' + (project?.name ?? projectId) + ' — LINUP App Package\n\nGenerated: ' + new Date().toISOString() + '\n\nSee specification/ for the full engineering specification.\n';
  archive.append(readme, { name: 'README.md' });
  await archive.finalize();
  await new Promise<void>((resolve, reject) => { output.on('finish', resolve); output.on('error', reject); archive.on('error', reject); });
  return Buffer.concat(chunks);
}

export async function uploadAndRecord(projectId: string, zipBuffer: Buffer, db: SupabaseClient): Promise<string> {
  const { data: project } = await db.from('projects').select('slug').eq('id', projectId).single();
  const slug = project?.slug ?? projectId;
  const filename = getZipFilename(slug);
  const storagePath = 'app-packages/' + projectId + '/' + filename;
  const storage = db.storage;
  await storage.from('app-packages').upload(storagePath, zipBuffer, { contentType: 'application/zip', upsert: true });
  const { data: signedData } = await storage.from('app-packages').createSignedUrl(storagePath, 86400);
  const signedUrl = signedData?.signedUrl ?? '';
  await db.from('download_events').insert({
    project_id: projectId, download_type: 'APP', storage_path: storagePath, download_url: signedUrl,
    download_url_expires_at: new Date(Date.now() + 86400_000).toISOString(),
    artifact_expires_at: new Date(Date.now() + 90 * 86400_000).toISOString(),
    created_at: new Date().toISOString(),
  });
  console.log('[zip-generator] ZIP uploaded: ' + storagePath);
  return signedUrl;
}